image: google/dart

before_script:
  - export PATH="$PATH":"~/.pub-cache/bin"
  - pub global activate grinder

test:
  stage: test
  script:
  - pub get
  - grind test

pages:
  stage: deploy
  script:
  - pub get
  - grind doc
  artifacts:
    paths:
    - public
  only:
  - master

publish:
  stage: deploy
  script:
  - ci/publish.sh
  only:
  - master