image: google/dart

before_script:
  - export PATH="$PATH":"~/.pub-cache/bin"
  - pub global activate grinder
  - pub get

test:
  stage: test
  script:
  - grind test

pages:
  stage: deploy
  script:
  - grind doc
  artifacts:
    paths:
    - public
  only:
  - master

publish:
  stage: deploy
  script:
  - grind ci-publish
  only:
  - master