name: gitlab
version: 0.1.0
description: A library to communicate with the GitHub API
environment:
  sdk: ^1.21.0
dependencies:
  http: ^0.11.2
  logging: ^0.11.0
  intl: ^0.14.0
  meta: ^1.0.0
dev_dependencies:
  test: ^0.12.6
  mockito: ^1.0.1
  grinder: ^0.8.0