name: gitlab
version: 0.2.2
description: A library to communicate with the GitLab API
homepage: https://gitlab.com/exitlive/gitlab-dart
documentation: http://exitlive.gitlab.io/gitlab-dart/
author: Matias Meno <m@tias.me>
environment:
  sdk: ">=1.21.0 <2.0.0"
dependencies:
  http: ^0.11.2
  logging: ^0.11.0
  intl: ^0.14.0
  meta: ^1.0.0
dev_dependencies:
  test: ^0.12.20
  path: ^1.4.0
  mockito: ^1.0.1
  grinder: ^0.8.0
  pub_client: ^1.0.0
